
name: Deploy new build to gh-pages for activation.

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm run deploy
