name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with gh-pages
        run: |
          npx gh-pages -d build --add --user "mysoladi" --email "mysoladine@gmail.com"
